version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    env_file:
      - docker.env
      
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: npm run start:dev
  postgres:
    image: postgres:latest
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - docker.env
    ports:
      - "8000:80"
    restart: on-failure 